# Generated by Django 5.2 on 2025-04-25 20:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_operator_center'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operator',
            name='incharge',
        ),
        migrations.AddField(
            model_name='operator',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operators_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
